services:
  byte-server:
    image: node-byte-server
    container_name: byte-server
    environment:
      - TZ=Europe/Berlin
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.bytes.rule=Host(`bytes.example.com`) || PathPrefix(`/bytes`)
      - traefik.http.services.bytes.loadbalancer.server.port=3000
    ports:
      - 3030:3000

networks:
  proxy:
    name: proxy
    external: true